language: node_js
node_js:
    - "6.1"

services:
    - mongodb

script:
    - npm test

after_script:
    - CODECLIMATE_REPO_TOKEN=7a311c3f494eb5dec48411c6682501d4eb7c4cb7ab5ce9d78f32429a8da86a2e codeclimate-test-reporter < ./coverage/lcov.info

addons:
    code_climate:
        repo_token: 7a311c3f494eb5dec48411c6682501d4eb7c4cb7ab5ce9d78f32429a8da86a2e
